// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_submissions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteContactSubmission = `-- name: DeleteContactSubmission :exec
DELETE FROM contact_submissions
WHERE id = $1
`

func (q *Queries) DeleteContactSubmission(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteContactSubmission, id)
	return err
}

const getContactSubmission = `-- name: GetContactSubmission :one
SELECT id, name, email, message, ip_address, created_at FROM contact_submissions
WHERE id = $1
`

func (q *Queries) GetContactSubmission(ctx context.Context, id string) (ContactSubmission, error) {
	row := q.db.QueryRow(ctx, getContactSubmission, id)
	var i ContactSubmission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const insertContactSubmission = `-- name: InsertContactSubmission :one

INSERT INTO contact_submissions (name, email, message, ip_address)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, message, ip_address, created_at
`

type InsertContactSubmissionParams struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	Message   string `json:"message"`
	IpAddress string `json:"ip_address"`
}

// Auto-generated CRUD queries for contact_submissions
// Edit as needed, then run: db codegen
func (q *Queries) InsertContactSubmission(ctx context.Context, arg InsertContactSubmissionParams) (ContactSubmission, error) {
	row := q.db.QueryRow(ctx, insertContactSubmission,
		arg.Name,
		arg.Email,
		arg.Message,
		arg.IpAddress,
	)
	var i ContactSubmission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listContactSubmissions = `-- name: ListContactSubmissions :many
SELECT id, name, email, message, ip_address, created_at FROM contact_submissions
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListContactSubmissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListContactSubmissions(ctx context.Context, arg ListContactSubmissionsParams) ([]ContactSubmission, error) {
	rows, err := q.db.Query(ctx, listContactSubmissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactSubmission{}
	for rows.Next() {
		var i ContactSubmission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Message,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactSubmissionsByEmailAndCreatedAt = `-- name: ListContactSubmissionsByEmailAndCreatedAt :many
SELECT id, name, email, message, ip_address, created_at FROM contact_submissions
WHERE email = $1 AND created_at >= $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListContactSubmissionsByEmailAndCreatedAtParams struct {
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
}

func (q *Queries) ListContactSubmissionsByEmailAndCreatedAt(ctx context.Context, arg ListContactSubmissionsByEmailAndCreatedAtParams) ([]ContactSubmission, error) {
	rows, err := q.db.Query(ctx, listContactSubmissionsByEmailAndCreatedAt,
		arg.Email,
		arg.CreatedAt,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactSubmission{}
	for rows.Next() {
		var i ContactSubmission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Message,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
