// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ContactSubmission struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Message   string             `json:"message"`
	IpAddress string             `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OauthAuthorizationCode struct {
	Code          string             `json:"code"`
	ClientID      string             `json:"client_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	RedirectUri   string             `json:"redirect_uri"`
	Scopes        []string           `json:"scopes"`
	CodeChallenge string             `json:"code_challenge"`
	Nonce         string             `json:"nonce"`
	Used          bool               `json:"used"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type OauthClient struct {
	ID           pgtype.UUID        `json:"id"`
	ClientID     string             `json:"client_id"`
	ClientSecret string             `json:"client_secret"`
	Name         string             `json:"name"`
	RedirectUris []string           `json:"redirect_uris"`
	Scopes       []string           `json:"scopes"`
	Public       bool               `json:"public"`
	FirstParty   bool               `json:"first_party"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OauthConsent struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ClientID  string             `json:"client_id"`
	Scopes    []string           `json:"scopes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OauthToken struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash string             `json:"token_hash"`
	TokenType string             `json:"token_type"`
	ClientID  string             `json:"client_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Scopes    []string           `json:"scopes"`
	Revoked   bool               `json:"revoked"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type QueueJob struct {
	ID          pgtype.UUID        `json:"id"`
	Queue       string             `json:"queue"`
	Priority    int32              `json:"priority"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	LastError   string             `json:"last_error"`
	RunAt       pgtype.Timestamptz `json:"run_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Role        string             `json:"role"`
	Verified    bool               `json:"verified"`
	WebauthnID  []byte             `json:"webauthn_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WebauthnCredential struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CredentialID    []byte             `json:"credential_id"`
	Name            string             `json:"name"`
	PublicKey       []byte             `json:"public_key"`
	PublicKeyAlg    int64              `json:"public_key_alg"`
	AttestationType string             `json:"attestation_type"`
	Aaguid          []byte             `json:"aaguid"`
	SignCount       int64              `json:"sign_count"`
	CloneWarning    bool               `json:"clone_warning"`
	BackupEligible  bool               `json:"backup_eligible"`
	BackupState     bool               `json:"backup_state"`
	Transports      []string           `json:"transports"`
	Attachment      string             `json:"attachment"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
