// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const complete = `-- name: Complete :exec
UPDATE queue_jobs
SET status = 'completed', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) Complete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, complete, id)
	return err
}

const dequeue = `-- name: Dequeue :one
WITH next AS (
    SELECT id FROM queue_jobs
    WHERE queue_jobs.queue = ANY($1::text[])
      AND status = 'pending'
      AND run_at <= NOW()
    ORDER BY priority ASC, run_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE queue_jobs
SET status = 'running',
    attempts = attempts + 1,
    updated_at = NOW()
FROM next
WHERE queue_jobs.id = next.id
RETURNING queue_jobs.id, queue_jobs.queue, queue_jobs.priority,
          queue_jobs.payload, queue_jobs.status, queue_jobs.attempts,
          queue_jobs.max_attempts, queue_jobs.last_error, queue_jobs.run_at,
          queue_jobs.created_at, queue_jobs.updated_at
`

// Atomically claims the highest-priority pending job from the given queues.
// Uses FOR UPDATE SKIP LOCKED for concurrent-safe worker claiming.
func (q *Queries) Dequeue(ctx context.Context, dollar_1 []string) (QueueJob, error) {
	row := q.db.QueryRow(ctx, dequeue, dollar_1)
	var i QueueJob
	err := row.Scan(
		&i.ID,
		&i.Queue,
		&i.Priority,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueue = `-- name: Enqueue :one

INSERT INTO queue_jobs (queue, priority, payload, status, max_attempts, run_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at
`

type EnqueueParams struct {
	Queue       string          `json:"queue"`
	Priority    int32           `json:"priority"`
	Payload     json.RawMessage `json:"payload"`
	Status      string          `json:"status"`
	MaxAttempts int32           `json:"max_attempts"`
	RunAt       time.Time       `json:"run_at"`
}

type EnqueueRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Queue job queries.
// Query names and return modes follow sqlc conventions (-- name: X :one/:exec/:execrows).
// Generated Go code lives in db/ via the co-located .sqlc.yaml.
func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) (EnqueueRow, error) {
	row := q.db.QueryRow(ctx, enqueue,
		arg.Queue,
		arg.Priority,
		arg.Payload,
		arg.Status,
		arg.MaxAttempts,
		arg.RunAt,
	)
	var i EnqueueRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const fail = `-- name: Fail :exec
UPDATE queue_jobs
SET last_error  = $1,
    updated_at  = NOW(),
    status      = CASE WHEN attempts >= max_attempts THEN 'dead' ELSE 'pending' END,
    run_at      = CASE WHEN attempts >= max_attempts THEN run_at ELSE NOW() + $2::interval END
WHERE id = $3
`

type FailParams struct {
	LastError  string          `json:"last_error"`
	RetryAfter pgtype.Interval `json:"retry_after"`
	ID         uuid.UUID       `json:"id"`
}

// Reschedules a job for retry or marks it dead.
func (q *Queries) Fail(ctx context.Context, arg FailParams) error {
	_, err := q.db.Exec(ctx, fail, arg.LastError, arg.RetryAfter, arg.ID)
	return err
}

const reap = `-- name: Reap :execrows
UPDATE queue_jobs
SET status = 'pending', updated_at = NOW()
WHERE id IN (
    SELECT id FROM queue_jobs
    WHERE queue_jobs.queue = ANY($1::text[])
      AND status = 'running'
      AND updated_at < NOW() - $2::interval
    FOR UPDATE SKIP LOCKED
)
`

type ReapParams struct {
	Queues     []string        `json:"queues"`
	StaleAfter pgtype.Interval `json:"stale_after"`
}

// Reclaims running jobs stuck beyond the stale threshold.
func (q *Queries) Reap(ctx context.Context, arg ReapParams) (int64, error) {
	result, err := q.db.Exec(ctx, reap, arg.Queues, arg.StaleAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
