baseURL = "/docs/"
title = "Documentation"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]

[params]
  description = "Documentation for this application."

[markup]
  [markup.goldmark.renderer]
    unsafe = false
  [markup.highlight]
    codeFences = true
    noClasses = false

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "assets"
    target = "assets"
