package secure

import (
	"github.com/go-sum/web"
)

// defaultCSPWithNonce is the CSP policy used by SecureDefaults. It includes
// 'nonce-{nonce}' placeholders that CSPNonce replaces with a fresh per-request value.
const defaultCSPWithNonce = "default-src 'self'; script-src 'self' 'nonce-{nonce}'; style-src 'self' 'nonce-{nonce}'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; object-src 'none'"

// SecureDefaults returns a composite middleware that installs a production-ready
// security baseline in a single call. It chains, in order:
//
//  1. AsyncContext — stores *web.Context inside the underlying context.Context for
//     deep-call access via web.FromContext without explicit parameter plumbing.
//  2. Headers — sets strict security headers (non-clobber; per-handler overrides win).
//  3. CSPNonce — generates a fresh 128-bit nonce per request and injects it into the
//     Content-Security-Policy header. Use Nonce(c) in templates for inline scripts/styles.
//
// The Content-Security-Policy set by Headers middleware is superseded by the nonce-aware
// policy generated by CSPNonce (response-path: nonce sets first, headers skips via setIfAbsent).
// Panic recovery is handled by web.ErrorBoundary, which must be installed in the chain.
func SecureDefaults() web.Middleware {
	async := web.AsyncContext()
	hdrs := Headers(DefaultHeadersConfig())
	nonce := CSPNonce(CSPNonceConfig{CSPTemplate: defaultCSPWithNonce})

	return func(next web.Handler) web.Handler {
		// Execution order on request:  async → hdrs → nonce → handler
		// Execution order on response: handler → nonce → hdrs → async
		// AsyncContext is outermost so the context is available to all inner middleware.
		// nonce sets CSP first; hdrs' setIfAbsent skips it.
		return async(hdrs(nonce(next)))
	}
}
